---
- name: Remove default nginx vhost
  file:
    path: "{{ nginx_default_vhost }}"
    state: absent
  notify: reload nginx

- name: Add managed vhost config files.
  template:
    src: "vhost.conf.j2"
    dest: "{{ nginx_vhost_path }}/{{ item.server_name }}.conf"
    force: "true"
    owner: "root"
    group: "root"
    mode: "0644"
  when: item.state|default('present') != 'absent'
  with_items: "{{ nginx_vhosts }}"
  notify: reload nginx
