---
# Create SSL Certificates
- name: Make sure certbot packages are present
  package:
    name:
      - certbot
      - python3-certbot-dns-cloudflare
    state: present

# These credentials are stored in Tower vault.
# Credentials are accessed with variables through an injector
- name: Create cloudflare credentials file for certbot
  copy:
    dest: "/etc/ssl/cloudflare_key"
    mode: "0600"
    content: |
      dns_cloudflare_email = {{ cloudflare_email }}
      dns_cloudflare_api_key = {{ cloudflare_api_key }}

- name: Create certificates
  shell: |
    certbot certonly --dns-cloudflare \
    --dns-cloudflare-credentials /etc/ssl/cloudflare_key \
    -d "{{ item.website_name }}" --non-interactive \
    --agree-tos -m "{{ item.admin_email | default('acintasv@gmail.com') }}"
  with_items: "{{ websites }}"
  when: item.state|default('present') != 'absent'

# Create defined Vhosts
- name: Add managed vhost config files.
  template:
    src: "vhost.conf.j2"
    dest: "{{ nginx_vhost_path }}/{{ item.website_name }}.conf"
    force: "true"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items: "{{ websites }}"
  when: item.state|default('present') != 'absent'
  notify: reload nginx

# Configure DNS records
- name: Update A record for new vhosts
  shell: |
    URL="{{ cf_url }}/{{ item.cf_zone }}/dns_records/{{ item.cf_record }}"
    curl -X PUT "$URL" \
     -H "X-Auth-Email: {{ cloudflare_email }}" \
     -H "X-Auth-Key: {{ cloudflare_api_key }}" \
     -H "Content-Type: application/json" \
     --data '{"type":"A",\
              "name":"{{ item.website_name }}",\
              "content":"{{ ansible_ssh_host }}",\
              "ttl":{{ item.cloudflare_ttl | default('360') }},\
              "proxied":false}'
  with_items: "{{ websites }}"
  when: item.state|default('present') != 'absent'
  args:
    # Ansible wants us to use a module instead of curl
    warn: false
