---
- name: Install Nginx and deploy a list of websites from Github
  # Use dynamic inventory and tags from AWS instances.
  hosts: tag_Role_Webserver
  vars:
    # A list of websites to be configured/deployed can be defined below.
    # If nothing is defined, the playbook just installs and configures Nginx.
    websites:
      - listen_https: 8080
        website_name: "awonderfultestdomain.xyz"
        # Github repo vars
        # Release tag is grabbed from Tower webhook after release creation.
        git_repo: "https://github.com/AlbertCintas/my-cv-in-html.git"
        git_tag: "{{ tower_webhook_event_ref | default('main') }}"
        # Cloudflare API vars for DNS records.
        cf_zone: "1cb53cf7889cb870d8af297cb556d022"
        cf_record: "bda529c48eac4bb0ac30ed84c881d695"
  roles:
   - nginx
   - nginx-git-deploy
  pre_tasks:
    # We wait for connection in case this playbook is run inmediately after.
    # an instance has been deployed.
    - name: Wait for newly created hosts to become available.
      wait_for_connection:
