---
# Nginx configuration default values
nginx_worker_processes: "{{ ansible_processor_vcpus | default(auto) }}"
nginx_worker_connections: "768"
nginx_multi_accept: "off"
nginx_client_max_body_size: "64m"
nginx_sendfile: "on"
nginx_tcp_nopush: "on"
nginx_tcp_nodelay: "on"
nginx_keepalive_timeout: "65"
nginx_types_hash_max_size: "2048"
nginx_server_tokens: "on"
nginx_error_log: "/var/log/nginx/error.log debug"
nginx_access_log: "/var/log/nginx/access.log main buffer=16k flush=2m"
nginx_ssl_protocols: "TLSv1 TLSv1.1 TLSv1.2 TLSv1.3"
ssl_prefer_server_ciphers: "on"
nginx_gzip: "on"