---
- name: Checkout git repository for website
  git:
    repo: "{{ item.git_repo }}"
    dest: "/var/www/{{ item.website_name }}"
    version: "{{ item.git_tag | default('main') }}"
    force: yes
  become: yes
  become_user: "{{ nginx_user }}"
  with_items: "{{ websites }}"
  when: item.state|default('present') != 'absent'
