---
# Prepare environment
- name: Include OS variables.
  include_vars: "{{ ansible_distribution }}.yml"

# Deploy
- name: Checkout git repository for website
  git:
    repo: "{{ item.git_repo }}"
    dest: "/var/www/{{ item.website_name }}"
    version: "{{ item.git_tag | default('main') }}"
    force: true
  with_items: "{{ websites }}"
  when: item.state|default('present') != 'absent'

- name: Chown web folder
  file:
    path: "/var/www/{{ item.website_name }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    recurse: true
  with_items: "{{ websites }}"
  when: item.state|default('present') != 'absent'
