---
- name: Deploy repository ssh key

- name: Checkout git repository
  git:
    repo: 'git@github.com:{{ web_repository }}'
    dest: /var/www/{{ websites.website_name }}
    version: {{ version }}
    accept_hostkey: yes
    force: yes
    key_file: /home/{{ nginx_user }}/.ssh/id_rsa_{{ websites.website_name }}
      
- name: Chown web folder
  file:
    path: /var/www/{{ websites.website_name }}
    owner: {{ nginx_user }}
    group: {{ nginx_user }}
    recurse: yes