---
- name: Checkout git repository for website
  git:
    repo: "{{ item.git_repo }}"
    dest: "/var/www/{{ item.website_name }}"
    version: "{{ item.git_tag | default('main') }}"
    force: yes
  with_items: "{{ websites }}"
  when: item.state|default('present') != 'absent'

- name: Chown web folder
  file:
    path: /var/www/{{ item.website_name }}
    owner: {{ nginx_user }}
    group: {{ nginx_user }}
    recurse: yes
  with_items: "{{ websites }}"
  when: item.state|default('present') != 'absent'
