---
- name: Converge
  hosts: all
  vars:
    # For the sake of simplicity we use the main example vars for testing
    websites:
      - website_name: "awonderfultestdomain.xyz"
        git_repo: "https://github.com/AlbertCintas/my-cv-in-html.git"
        git_tag: "{{ tower_webhook_event_ref | default('main') }}"
  tasks:
    - name: "Include nginx-git-deploy"
      include_role:
        name: "nginx-git-deploy"
  pre_tasks:
    - name: Install git.
      apt: name=git state=present update_cache=yes
      when: ansible_os_family == 'Debian'
      changed_when: false
