---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: Ubuntu-Latest
    image: ubuntu:latest
  - name: CentOS-7
    image: centos:7
provisioner:
  name: ansible
verifier:
  name: ansible
