---
name: Molecule CI
'on':
  pull_request:
  push:
    branches:
      - main

jobs:
  molecule:
    name: Molecule Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - ubuntu2004
          # Other distros can be added here
          #- centos8

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install ansible molecule[docker] docker

      # As many role secrets are stored in the Tower vault and not shared
      # in Github, the tests fail. For the sake of simplicity we skip the
      # tests of this role.
      # In a real environment secrets could be shared to Github
      # Actions through secrets or an external shared vault.
      #
      # - name: Run Molecule tests on Nginx role.
      #   run: molecule test
      #   working-directory: ./roles/nginx/
      #   env:
      #     PY_COLORS: '1'
      #     ANSIBLE_FORCE_COLOR: '1'
      #     MOLECULE_DISTRO: ${{ matrix.distro }}

      - name: Run Molecule tests on Nginx deploy role.
        run: molecule test
        working-directory: ./roles/nginx/nginx-git-deploy
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
